name: Deploy to Netlify

on:
  push:
    branches:
      - main  # Change this to your main branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Netlify CLI
        run: npm install netlify-cli -g

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: netlify deploy --prod
